### ISSUE TITLE
Treat all read/populate scenarios in new code

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/Bulk-Load#143]
Right now we have the following:

- [x] Fill by Row
- [ ] Fill by Column
- [x] Fill by Cell
- [x] Read by Row
- [ ] Read by Column
- [x] Read by Cell

After adding tracker we found out that this might add a lot of complexity to treat all scenarios. Instead we should try to push towards:
- [ ] Fill by cell aggregated
- [ ] Fill by cell events
- [ ] Fill by cell tracker (and its different types)

And subtypes "row" and "column" internally call the "cell" method.

Idea:

∀ Data Package (with a given cell from fixed or range (aka row/column)):
  - Set period
  - Set org unit
  - Set attribute (if exists)
  - Set event id (if exists)
  - ∀ Data Value
    - Lookup dataElement and category from current cell
    - Write value

**Comment by adrianq** [comment]
This doesn't apply anymore as we will change the approach
