### ISSUE TITLE
Support TEI relationships with other programs

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/Bulk-Load#188]
Maybe we can download TEIs pointed by our relationship of our program. Very likely this will lead to a tab for each relationship type.

Instance: dhis2-ento-vc
Program: ENTO Mosquitos. 

Tasks:
- [x] Get only relationship types TEI<->TEI and one of them assignable to the tracker program.
- [x] Create a tab for each relationship type
- [x] Check from/to not corresponding to their types, they may be are swapped from DHIS

**Comment by tokland** [comment]
- N new tabs by Tracked Entity Types (protected)
        TEI Instances (Trauma Patient)
        TEI Instances (Person)

- N new tabs by Relationship 
        -> From TEI: as it is, from TEI instances
        -> To TEI shows only TEIs for that TET
    Mother-Child (Trauma Patient)
    Mother-Child (Person)

**Comment by ifoche** [comment]
[ENTO- Mosquito.xlsx](https://github.com/EyeSeeTea/Bulk-Load/files/5494054/ENTO-.Mosquito.xlsx)
[ENTO- Mosquito_updated2.xlsx](https://github.com/EyeSeeTea/Bulk-Load/files/5494056/ENTO-.Mosquito_updated2.xlsx)
