### ISSUE TITLE
Review responsiveness

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/Bulk-Load#73]
We need to discuss how to reorganise the layout. Two independent sections?
See https://github.com/EyeSeeTea/Bulk-Load-blessed/issues/2

Tasks:

- [x] Add router (w/ 4 routes: generation, import, settings, theme)
- [x] Create sidebar component (maps-app + improvements and simplify)
- [x] Extract components into pages (partially done in tests card)

For later (UX):

- [ ] Move page state to query-string location
- [ ] Cache page state between page transitions (do not forget state when moving through sidebar)

**Comment by SferaDev** [comment]
Mockup:
![image](https://app.gitkraken.com/api/glo/boards/5e1c3ced05746d0010cd4be3/attachments/5ec39b263c50160016726652)

**Comment by adrianq** [comment]
Moved to clickup
