### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/Bulk-Load#98]
- [x] OU tree on the right side. I guess the behaviour should be to download all events found at any OU in the tree, right? However, we are not downloading any data
- [x] Refresh Org Unit Tree when changing from Dataset to Program or the other way around.
- [x] Try to import it in another Org Unit when there is no data (array of undefineds)
- [x] Import for datasets fails if there are invalid Org unit (See https://github.com/EyeSeeTea/Bulk-Load/pull/93#issuecomment-633504582)
- [x] Limit width in Org Unit selector. Increase with for Org Unit filters

Later:
- [ ] Select user language by default. Show languages in use language, i.e. Ingles instead of English
- [ ] Investigate if we can show a sort of spinner/progress bar when changing dataset or program
- [ ] Also, it is a bit strange when we show the org unit at the beginning and the user cannot actually do anything with it. Maybe disable or hide it? (Disable + hide on checkbox and orgUnitTree)
- [ ] Review styling in confirmation modal (in particular the buttons)

**Comment by adrianq** [comment]
Moved to clickup
